POST http://localhost:3333/tarefa/create
Content-Type: application/json

{
        "descricao" : 2,
        "categoria" : "estudar",
        "status" : "pendente",
        "horaCriacao" : "07:00",
        "horaFinal" : "09:00"
}

###

GET  http://localhost:3333/tarefas


###
PUT http://localhost:3333/tarefa/3561cbad-c3ef-4eb7-ad87-94cfb39f923e
Content-Type: application/json

{
        "descricao" : "1",
        "categoria" : "estudar",
        "status" : "concluido",
        "horaCriacao" : "07:02",
        "horaFinal" : "09:02"
}

###

DELETE http://localhost:3333/tarefa/49e9414b-8781-42cd-9358-bf161da2ba3f

###

POST http://localhost:3333/meta/create
Content-Type: application/json

{"descricao":"CVXCVXCV","categoria":"financeiro",
    "periodo":"semana","status":"pendente","dataCriacao":"2025-08-20","dataFinal":"2025-08-24"}

# descricao: z.string(),
    
#     categoria: z.string(),

#     periodo: z.string(),

#     status: z.string(),
  
#     dataCriacao: z.string(),
  
#     dataFinal: z.string()
#     .optional(), 

#     dataConcluida: z.string().nullable().optional()


