POST http://localhost:3333/tarefa/create
Content-Type: application/json

{
        "descricao" : "dsvasdvjahd",
        "categoria" : "estudar",
        "status" : "pendente",
        "horaCriacao" : "07:00",
        "horaFinal" : "09:00",
        "horaConclusao" : ""
}

###

GET  http://localhost:3333/tarefas

###

GET  http://localhost:3333/tarefas?search=estudar


###
PUT http://localhost:3333/tarefa/01faeb6a-b51c-401c-b8d9-33bcdbb5a218
Content-Type: application/json

{
        "descricao" : "dsvasdvjahd",
        "categoria" : "financeiro",
        "status" : "pendente",
        "horaCriacao" : "07:00",
        "horaFinal" : "09:00",
        "horaConclusao" : "20:00"
}

###

DELETE http://localhost:3333/tarefa/01faeb6a-b51c-401c-b8d9-33bcdbb5a218

###

POST http://localhost:3333/meta/create
Content-Type: application/json

{"descricao":"as","categoria":"financeiro",
    "periodo":"semana","status":"pendente","dataCriacao":"2025-08-20","dataFinal":"2025-08-24"}

###

GET  http://localhost:3333/meta/get

###

PUT  http://localhost:3333/meta/update/438a4a3f-64df-4b20-90d6-791b37e46a8f
Content-Type: application/json

{"descricao":"Atualizado","categoria":"1212",
    "periodo":"semana","status":"pendente","dataCriacao":"2025-08-20","dataFinal":"2025-08-24"}

###

DELETE http://localhost:3333/meta/delete/e0414508-b005-4a5f-8cc2-67cd069fd945