POST http://localhost:3333/tarefa/create
Content-Type: application/json

{
    "descricao": "sddafgsdfgsdfgsdfgvbdfg",
    "categoria": "estudar",
    "status": "pendente",
    "dataCriacao": "2025-09-10T07:00:00Z",
    "dataFinal": "2025-09-10T09:00:00Z",
    "dataConcluida": null
}

###

GET  http://localhost:3333/tarefas

###

GET  http://localhost:3333/tarefa/1

###
PUT http://localhost:3333/tarefa/2
Content-Type: application/json

{
    "descricao": "teste2atualizando",
    "categoria": "estudar",
    "status": "pendente",
    "dataCriacao": "2025-09-10T07:00:00Z",
    "dataFinal": "2025-09-10T09:00:00Z",
    "dataConcluida": "Concluida"
}

###

DELETE http://localhost:3333/tarefa/6







### 

POST http://localhost:3333/meta/create
Content-Type: application/json

{   "descricao":"Teste",
    "categoria":"Financeiro",
    "periodo":"semana",
    "status":"Pendente",
    "dataCriacao":"2025-08-20",
    "dataFinal":"2025-08-24",
    "dataConcluida":"2025-08-24"}

###

GET  http://localhost:3333/meta/getAll

###

GET  http://localhost:3333/meta/get/4

###

PUT  http://localhost:3333/meta/update/1
Content-Type: application/json

{"descricao":"Atualizando","categoria":"Financeiro",
    "periodo":"semana","status":"Pendente","dataCriacao":"2025-08-20","dataFinal":"2025-08-24","dataConcluida":"2025-08-24"}

###

DELETE http://localhost:3333/meta/delete/1

###

POST http://localhost:3333/lembrete/create
Content-Type: application/json

{
  "descricao": "Estudar para a prova de PLP"
}

###

get http://localhost:3333/lembrete/getAll

###

delete http://localhost:3333/lembrete/delete/1
